#! /bin/bash

function addusr2grp()
{
 sgrpname=`grep -w ${grpname} /etc/aliases1`
 cgrpname="${sgrpname}, ${usrname}"
 sed "s/${sgrpname}/${cgrpname}/" /etc/aliases1 > /etc/aliasestmp
 cp /etc/aliasestmp /etc/aliases1
 rm /etc/aliasestmp
}

case $1 in
 -a | -A)
  grpname=$6
  usrname=$2
  if [ $# -eq 6 ]; then
   sgr=`grep -w $6 /etc/aliases | wc -l`
   lgname=`grep -w ${usrname} /etc/passwd | wc -l`
   if [ ${sgr} -le 0 ]; then
    echo 'Group "'${6}'" Not Exist'
   elif [ ${lgname} -gt 0 ]; then
    echo 'User "'${2}'" already Exist'
   else
    useradd $2 -d /home/$2 -g ltsgrp -p $3 -s /sbin/nologin -c $4
    addusr2grp;
   fi
  else
    clear
    echo 'Usage Example.............'
    echo 'usr -a Loginname Password Descript sendout Group'
  fi
;;

 -d | -D)
  if [ $# -eq 2 ]; then
   lgname=`grep -w $2 /etc/passwd | wc -l`
   if [ ${lgname} -le 0 ]; then
    echo 'User "'${2}'" Not Exist'
   else
    userdel $2
   fi
  else
   clear
   echo 'Usage Example.............'
   echo 'usr -d LoginName'
  fi
;;

 -m | -M)
  if [ $# -eq 3 ]; then
    lgname=`grep -w $2 /etc/passwd | wc -l`
    if [ ${lgname} -le 0 ];then
      echo 'User "'${2}'" Not Exist'
    else
      echo 'change User Name'
    fi
  else
    clear
    echo 'Usage Example ...........'
    echo 'usr -m account NewUserName'
  fi
;;

 *)
clear
echo 'usage : usr [option] Login ......'
echo '   usr -a Loginname Password Descript Sendout Group'
echo '     add a new user '
echo '   usr -d Loginname'
echo '     del a user'
echo '   usr -m Loginname UserName'
echo '     Change user name'
;;
esac
